# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.SmallIntegerField(choices=[(0, 'Character'), (1, 'Corporation'), (2, 'Alliance')])),
                ('name', models.CharField(max_length=255)),
                ('entityID', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='capsuler',
            name='claims',
            field=models.ManyToManyField(to='accounting.AccessClaim'),
        ),
    ]
