# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 22:24
from __future__ import unicode_literals

from django.utils import timezone
import pytz
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20170212_1313'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accessclaim',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='accessclaim',
            name='valid_until',
            field=models.DateTimeField(default=timezone.datetime(2099, 12, 31, 0, 0, tzinfo=pytz.UTC)),
        ),
        migrations.AlterField(
            model_name='accessclaim',
            name='entity_type',
            field=models.SmallIntegerField(choices=[(0, 'Character'), (1, 'Corporation'), (2, 'Alliance'), (3, 'Faction'), (4, 'Token')]),
        ),
    ]
